import Head from "next/head";
import Image from "next/image";
import { Baloo_Bhaijaan_2 } from "next/font/google";
import styles from "@/styles/Home.module.css";

const inter = Baloo_Bhaijaan_2({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <header className={styles.header}>
          <Image src="/assets/logo.png" alt="" width={400} height={150} />
        </header>
        <nav className={styles.nav}>
          <div className={styles.buttonContainer}>
            <button className={styles.navButton}>About Me</button>
            <button className={styles.navButton}>Home</button>
            <button className={styles.navButton}>Shop</button>
          </div>
        </nav>
        <section className={styles.candyStripe}>
          <ul>
            <li className={styles.stripe}></li>
            <li className={styles.stripe}></li>
            <li className={styles.stripe}></li>
            <li className={styles.stripe}></li>
            <li className={styles.stripe}></li>
            <li className={styles.stripe}></li>
            <li className={styles.stripe}></li>
            <li className={styles.stripe}></li>
            <li className={styles.stripe}></li>
            <li className={styles.stripe}></li>
          </ul>
        </section>
        <section className={styles.app}>
          <div className={styles.cardContainer}>
            <div className={styles.displayCard}>
              <Image src="/assets/doll.png" alt="" width={320} height={300} />
              <div className={styles.cardContent}>
                <h2 className={styles.cardTitle}>Doll</h2>
                <p className={styles.cardText}>
                  Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis
                  eleifend neque turpis, dictum rhoncus enim condimentum eget.
                  Aliquam quis aliquet.
                </p>
              </div>
            </div>
            <div className={styles.displayCard}>
              <Image src="/assets/split.png" alt="" width={320} height={300} />
              <div className={styles.cardContent}>
                <h2 className={styles.cardTitle}>Bannana Split</h2>
                <p className={styles.cardText}>
                  Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis
                  eleifend neque turpis, dictum rhoncus enim condimentum eget.
                  Aliquam quis aliquet.
                </p>
              </div>
            </div>
            <div className={styles.displayCard}>
              <Image
                src="/assets/planter.png"
                alt=""
                width={320}
                height={300}
              />
              <div className={styles.cardContent}>
                <h2 className={styles.cardTitle}>Plant Potter</h2>
                <p className={styles.cardText}>
                  Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis
                  eleifend neque turpis, dictum rhoncus enim condimentum eget.
                  Aliquam quis aliquet.
                </p>
              </div>
            </div>
          </div>
        </section>
        <footer className={styles.footer}>
          <p className={styles.footerText}>
            All photos and designs are copyright of Crochetes by Dee unless
            otherwise noted. Please do not repost or claim my content as your
            own.
          </p>
        </footer>
      </main>
    </>
  );
}
