/* eslint-disable react/jsx-key */
import Head from "next/head";
import Image from "next/image";
import { Baloo_Bhaijaan_2 } from "next/font/google";
import styles from "@/styles/Home.module.css";

const inter = Baloo_Bhaijaan_2({ subsets: ["latin"] });
const imageAssets = [
  "Cacti.png",
  "Doll.png",
  "Planter.png",
  "Planter2.png",
  "Roses.png",
  "Split.png",
  "Succulent.png",
];

export default function Home() {
  return (
    <>
      <Head>
        <title>Crochetes By Dee</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <section className={styles.app}>
          <div className={styles.homeFeed}>
            {imageAssets.map((photo, index) => {
              return (
                <div className={styles.cardContainer}>
                  <div className={styles.displayCard} id={`${index}`}>
                    <Image
                      src={`/assets/${photo}`}
                      alt=""
                      width={320}
                      height={300}
                      className={styles.homeImage}
                    />
                    <h2 className={styles.cardTitle}>
                      {photo.slice(0, photo.length - 4)}
                    </h2>
                    <p className={styles.cardText}>
                      {" "}
                      <b>Sold Out</b>
                    </p>
                  </div>
                </div>
              );
            })}
            {/* <Image src="/assets/doll.png" alt="" width={320} height={300} />
              <div className={styles.cardContent}>
                <h2 className={styles.cardTitle}>Doll</h2>
                <p className={styles.cardText}>
                  Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis
                  eleifend neque turpis, dictum rhoncus enim condimentum eget.
                  Aliquam quis aliquet.
                </p>
              </div>
            </div>
            <div className={styles.displayCard}>
              <Image src="/assets/split.png" alt="" width={320} height={300} />
              <div className={styles.cardContent}>
                <h2 className={styles.cardTitle}>Bannana Split</h2>
                <p className={styles.cardText}>
                  Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis
                  eleifend neque turpis, dictum rhoncus enim condimentum eget.
                  Aliquam quis aliquet.
                </p>
              </div>
            </div>
            <div className={styles.displayCard}>
              <Image
                src="/assets/planter.png"
                alt=""
                width={320}
                height={300}
              />
              <div className={styles.cardContent}>
                <h2 className={styles.cardTitle}>Plant Potter</h2>
                <p className={styles.cardText}>
                  Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis
                  eleifend neque turpis, dictum rhoncus enim condimentum eget.
                  Aliquam quis aliquet.
                </p>
              </div>
            </div>
          </div> */}
          </div>
        </section>
      </main>
    </>
  );
}
